export const TEXT_INPUT_CHANGE = "[card] TEXT_INPUT_CHANGE";
export const TEXT_INPUT_UPDATE = "[card] TEXT_INPUT_UPDATE";
export const CHECKBOX_INPUT_CHANGE = "[card] CHECKBOX_INPUT_CHANGE";
export const CHECKBOX_INPUT_UPDATE = "[card] CHECKBOX_INPUT_UPDATE";
export const ALTSRBODY_CHANGE = "[card] ALTSRBODY_CHANGE";
export const ALTSRBODY_UPDATE = "[card] ALTSRBODY_UPDATE";
export const BODY_TEXT_EDITOR_CHANGE = "[card] BODY_TEXT_EDITOR_CHANGE";
export const BODY_TEXT_EDITOR_UPDATE = "[card] BODY_TEXT_EDITOR_UPDATE";
